import { useState, useEffect, useCallback } from 'react';
import { Link, useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, Plus, Play, Share2, LockKeyhole, Globe2, Search, Pencil, Trash2, Bookmark, Copy, History, RotateCcw, ArrowRight, Layers, Radio, Upload, Download, FileSpreadsheet, Swords, Heart } from 'lucide-react';
import { toast } from 'sonner';
import { api, imageUrl } from '../services/api';
import { reportError } from '../services/errors';
import { useApp, useQuery } from '../hooks/useApp';
import { useFolderRealtime } from '../hooks/useRealtime';
import { Button, Loading, ErrorState, Empty, FolderIcon, Avatar, Tag, Menu, Modal, Field } from '../components/ui';
import CardEditor from '../components/CardEditor';
import ShareModal from '../components/ShareModal';
import FolderModal from '../components/FolderModal';
import ImportModal from '../components/ImportModal';
import RichText, { sideOf, plainText } from '../components/RichText';
import Select, { optionsOf } from '../components/Select';
const describe = type => ({ 'card.created': 'added a card', 'card.updated': 'edited a card', 'card.deleted': 'deleted a card', 'cards.imported': 'imported cards', 'folder.updated': 'updated this folder', 'folder.members.changed': 'changed sharing', 'folder.archived': 'archived this folder' })[type] || type.replaceAll('.', ' ');
// Exports are cookie-authenticated GETs, so a plain download link works and the browser keeps the server's filename.
const download = url => { const a = document.createElement('a'); a.href = (import.meta.env.VITE_API_URL || '').replace(/\/$/, '') + url; a.download = ''; document.body.appendChild(a); a.click(); a.remove(); };
/** Picks quiz length and pace, then hands off to /rooms/new which creates the room over the socket. */
function QuizModal({ folder, cardCount, onClose }) {
  const navigate = useNavigate(); const [count, setCount] = useState(Math.min(10, cardCount)), [seconds, setSeconds] = useState(20);
  return <Modal open onClose={onClose} title="Host a live quiz" description={`Turn “${folder.title}” into a multiple-choice game. Friends join with a six-letter code; the fastest correct answers score the most.`}>
    <div className="two-columns"><Field label="Questions"><Select label="Questions" value={count} onChange={setCount} options={optionsOf([...[5, 10, 15, 20, 30].filter(n => n <= Math.max(2, cardCount)), ...(cardCount < 5 ? [cardCount] : [])], n => `${n} questions`)}/></Field><Field label="Seconds per question"><Select label="Seconds per question" value={seconds} onChange={setSeconds} options={optionsOf([10, 15, 20, 30, 45, 60], n => `${n} seconds`)}/></Field></div>
    <p className="help-copy">Each question shows a card’s front; the options are that card’s answer mixed with answers from other cards in this folder.</p>
    <div className="modal-actions"><Button type="button" className="secondary" onClick={onClose}>Cancel</Button><Button type="button" className="primary" onClick={() => navigate(`/rooms/new?folder=${folder.id}&count=${count}&seconds=${seconds}`)}><Swords size={16}/> Open the room</Button></div>
  </Modal>;
}
export default function FolderPage() {
  const { id } = useParams(); const { refresh, user } = useApp();
  const navigate = useNavigate();
  const [query, setQuery] = useState(''), [tag, setTag] = useState('all'), [flipped, setFlipped] = useState({}), [editor, setEditor] = useState(null), [share, setShare] = useState(false), [editFolder, setEditFolder] = useState(false), [remove, setRemove] = useState(null), [activity, setActivity] = useState(false), [bookmarkFilter, setBookmarkFilter] = useState(false), [liveVersions, setLiveVersions] = useState({}), [importing, setImporting] = useState(false), [quiz, setQuiz] = useState(false);
  // A socket event or the polling fallback reloads this one folder, not everything else on screen.
  const { data, error, loading, refetch: reload } = useQuery(`/folders/${id}`, () => Promise.all([api(`/folders/${id}`), api(`/folders/${id}/cards`)]).then(([f, c]) => ({ ...f, ...c })));
  // Live layer: committed events arrive over the socket; polling only runs as a fallback while disconnected.
  const { presence, connected, setEditing } = useFolderRealtime(id, {
    onEvent: e => { reload(); if (e.type === 'card.updated' && e.version != null) setLiveVersions(v => ({ ...v, [e.aggregateId]: e.version })); if (e.actor?.id !== user?.id) toast(`${e.actor?.name || 'Someone'} ${describe(e.type)}`, { description: e.detail?.slice(0, 80), icon: <Radio size={15}/> }); },
    onRevoked: () => { toast.error('Your access to this folder was removed.'); navigate('/'); }
  });
  useEffect(() => { if (connected) return; const timer = setInterval(() => { if (!document.hidden && !editor) reload(); }, 15000); return () => clearInterval(timer); }, [editor, connected, reload]);
  if (!data) return error ? <ErrorState message={error}/> : <Loading/>;
  const { folder, cards } = data; const canEdit = ['owner', 'editor'].includes(folder.role);
  // The server answers this per folder, because a team seat entitles its holder here and nowhere else.
  const unlocked = folder.premium;
  const others = presence.filter(p => p.user.id !== user?.id); const editingBy = Object.fromEntries(others.filter(p => p.editing).map(p => [p.editing, p]));
  const tags = [...new Set(cards.flatMap(c => c.tags))]; const filtered = cards.filter(c => (tag === 'all' || c.tags.includes(tag)) && (!bookmarkFilter || c.progress?.bookmarked) && `${c.front.text} ${c.back.text} ${c.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  const due = cards.filter(c => !c.progress?.dueAt || new Date(c.progress.dueAt) <= new Date()).length;
  async function bookmark(card) { try { await api(`/cards/${card.id}/bookmark`, { method: 'PATCH', body: { bookmarked: !card.progress?.bookmarked } }); refresh(); } catch (e) { reportError(e); } }
  return <><Link to="/" className="back-link"><ArrowLeft size={16}/> Back to library</Link>{error && <ErrorState message={error}/>}<div className="folder-page-heading">{folder.thumbnail ? <img className="folder-heading-thumb" src={imageUrl(folder.thumbnail)} alt=""/> : <div className={`large-folder-icon ${folder.color}`}><FolderIcon name={folder.icon} size={34}/></div>}<div><div className="folder-heading-meta"><span>{folder.visibility === 'global' ? <Globe2 size={13}/> : <LockKeyhole size={13}/>} {folder.visibility === 'global' ? 'Global collection' : 'Private collection'}</span>{folder.role === 'editor' && <span>Editor access</span>}</div><h1>{folder.title}</h1><p>{folder.description}</p></div><div className="folder-heading-actions"><Button className="secondary" onClick={() => setShare(true)}><Share2 size={16}/> Share</Button>{canEdit && <Button className="primary" onClick={() => setEditor({})}><Plus size={18}/> Add card</Button>}</div></div>
    <div className="folder-info-bar"><div><Avatar user={folder.owner} small/><span>Created by <Link to={`/u/${folder.owner?.username}`}><strong>@{folder.owner?.username}</strong></Link></span><span className="divider"/><span>{cards.length} cards</span><span className="divider"/><span><Heart size={12}/> {folder.likeCount || 0}</span><span className="divider"/><span><Copy size={12}/> {folder.copyCount || 0} copies</span>{folder.originalCreator && <span>Copied from @{folder.originalCreator}</span>}</div><div>{connected && <div className="presence-stack" title={others.length ? `Here now: ${others.map(p => p.user.name).join(', ')}` : 'You are the only one here'}>{others.slice(0, 4).map(p => <span className="presence-avatar" key={p.user.id} style={{ '--peer': p.color }}><Avatar user={p.user} small/></span>)}<span className="presence-label"><Radio size={12}/> {others.length ? `${others.length} here` : 'Live'}</span></div>}<button className="text-button" onClick={() => setActivity(true)}><History size={15}/> Activity</button><Menu items={[folder.role === 'owner' && { label: 'Edit folder', icon: <Pencil size={15}/>, action: () => setEditFolder(true) }, connected && cards.length >= 2 && { label: unlocked ? 'Host a live quiz' : 'Host a live quiz · Premium', icon: <Swords size={15}/>, action: () => unlocked ? setQuiz(true) : navigate('/premium') }, canEdit && { label: unlocked ? 'Import cards' : 'Import cards · Premium', icon: <Upload size={15}/>, action: () => unlocked ? setImporting(true) : navigate('/premium') }, { label: unlocked ? 'Export as JSON' : 'Export as JSON · Premium', icon: <Download size={15}/>, action: () => unlocked ? download(`/api/folders/${id}/export`) : navigate('/premium') }, { label: unlocked ? 'Export as CSV' : 'Export as CSV · Premium', icon: <FileSpreadsheet size={15}/>, action: () => unlocked ? download(`/api/folders/${id}/export?format=csv`) : navigate('/premium') }, { label: (folder.liked || folder.saved) ? 'Unlike' : 'Like', icon: <Heart size={15}/>, action: async () => { try { await api(`/folders/${id}/save`, { method: 'PATCH', body: { saved: !(folder.liked || folder.saved) } }); refresh(); } catch (e) { reportError(e); } } }, { label: 'Make a private copy', icon: <Copy size={15}/>, action: async () => { try { const d = await api(`/folders/${id}/copy`, { method: 'POST' }); refresh(); navigate(`/folders/${d.folder.id}`); } catch (e) { reportError(e); } } }]}/></div></div>
    {cards.length > 0 && <div className="folder-study-strip"><div><span className="study-strip-icon"><Layers size={25}/></span><div><h3>A little practice makes it stick.</h3><p>Flip a few cards, or settle into a focused study session.</p></div></div><div><Button className="secondary" onClick={() => navigate(`/folders/${id}/study?mode=all`)}>Quick review</Button><Button className="primary" disabled={!due} onClick={() => navigate(`/folders/${id}/study?mode=due`)}><Play size={16}/> Study due cards <span className="button-count">{due}</span></Button></div></div>}
    <div className="cards-toolbar"><h2>Flashcards <span>{cards.length}</span></h2><div><div className="folder-search"><Search size={16}/><input aria-label="Search flashcards" placeholder="Search cards or tags" value={query} onChange={e => setQuery(e.target.value)}/></div><Select compact label="Filter by tag" value={tag} onChange={setTag} options={optionsOf(['all', ...tags], t => (t === 'all' ? 'All tags' : t))}/><button className={`icon-button border-button ${bookmarkFilter ? 'selected' : ''}`} aria-label="Show bookmarked cards" aria-pressed={bookmarkFilter} onClick={() => setBookmarkFilter(v => !v)}><Bookmark size={18}/></button></div></div>
    {!filtered.length ? <Empty title={cards.length ? 'No cards match your filters' : 'Your first card starts here'} text={cards.length ? 'Try another keyword or tag.' : 'Add a question on the front and a memorable answer on the back.'} action={canEdit && !cards.length && <Button className="primary" onClick={() => setEditor({})}><Plus size={17}/> Create your first card</Button>}/> : <div className="flashcard-grid">{filtered.map((c, i) => { const side = sideOf(c, flipped[c.id]); return <article className={`flashcard-item ${flipped[c.id] ? 'is-flipped' : ''}`} key={c.id}><div className="flashcard-top"><span>{String(i + 1).padStart(2, '0')} <span> / {flipped[c.id] ? 'ANSWER' : 'QUESTION'}</span></span><div>{editingBy[c.id] && <span className="editing-badge" style={{ '--peer': editingBy[c.id].color }} title={`${editingBy[c.id].user.name} is editing this card`}><Pencil size={11}/> {editingBy[c.id].user.name.split(' ')[0]}</span>}<button aria-label={c.progress?.bookmarked ? 'Remove bookmark' : 'Bookmark card'} className={`icon-button ${c.progress?.bookmarked ? 'selected' : ''}`} onClick={() => bookmark(c)}><Bookmark size={16} fill={c.progress?.bookmarked ? 'currentColor' : 'none'}/></button>{canEdit && <Menu label={`Options for card ${i + 1}`} items={[{ label: 'Edit card', icon: <Pencil size={15}/>, action: () => setEditor(c) }, { label: 'Delete card', icon: <Trash2 size={15}/>, danger: true, action: () => setRemove(c) }]}/>}</div></div><button className="card-content" aria-label={`Flip card ${i + 1}`} onClick={() => setFlipped(f => ({ ...f, [c.id]: !f[c.id] }))}>{side.image && <img src={imageUrl(side.image)} alt={plainText(side.text) || 'Flashcard image'}/>}<RichText text={side.text} cloze={side.cloze}/></button><div className="flashcard-footer"><div>{c.tags.slice(0, 2).map(t => <Tag key={t}>{t}</Tag>)}</div><button className="text-button" onClick={() => setFlipped(f => ({ ...f, [c.id]: !f[c.id] }))}><RotateCcw size={13}/> Flip</button></div></article>; })}{canEdit && <button className="add-card-tile" onClick={() => setEditor({})}><span><Plus size={24}/></span><strong>Add a flashcard</strong><p>One more thing worth remembering.</p></button>}</div>}
    {editor && <CardEditor folder={folder} card={editor.id ? editor : null} onClose={() => setEditor(null)} onEditing={setEditing} liveVersion={editor.id ? liveVersions[editor.id] : null}/>} {share && <ShareModal folder={folder} onClose={() => setShare(false)}/>} {editFolder && <FolderModal folder={folder} onClose={() => setEditFolder(false)}/>} {importing && <ImportModal folder={folder} onClose={() => setImporting(false)}/>} {quiz && <QuizModal folder={folder} cardCount={cards.length} onClose={() => setQuiz(false)}/>} {activity && <ActivityModal id={id} onClose={() => setActivity(false)}/>}
    <Modal open={!!remove} onClose={() => setRemove(null)} title="Delete this flashcard?" description="This removes the card and its version history. This action cannot be undone."><div className="modal-actions"><Button className="secondary" onClick={() => setRemove(null)}>Keep card</Button><Button className="danger-button" onClick={async () => { try { await api(`/cards/${remove.id}`, { method: 'DELETE' }); setRemove(null); refresh(); toast.success('Card deleted'); } catch (e) { reportError(e); } }}>Delete card</Button></div></Modal>
  </>;
}
function ActivityModal({ id, onClose }) { const { data, loading, error } = useQuery(`/folders/${id}/activity`); return <Modal open onClose={onClose} title="Folder activity" description="Recent changes by people in this folder.">{loading ? <Loading/> : error ? <ErrorState message={error}/> : !data.activity.length ? <Empty title="A fresh start" text="Changes to this collection will appear here."/> : <div className="activity-list">{data.activity.map(a => <div key={a.id}><Avatar user={a.actor} small/><div><strong>{a.actor?.name} <span>{a.action.replaceAll('.', ' ')}</span></strong><p>{a.detail}</p><small>{new Date(a.createdAt).toLocaleString()}</small></div></div>)}</div>}</Modal>; }
