/**
 * Study collections aimed at United States exam candidates.
 *
 * Chosen for three things at once: a large American audience, a subject people are genuinely
 * motivated by rather than idly browsing, and material stable enough that a card written today is
 * still correct next year. Test preparation is also among the better-paying advertising categories,
 * which is the commercial half of the reason these exist.
 *
 * The answers are written out rather than clipped. A card that says only "1787" teaches nothing and
 * reads to a reviewer as scraped filler; one that says what happened and why it mattered is the
 * thing somebody actually wanted, and it is original writing rather than a copied answer key.
 *
 * `hint` is used where a nudge genuinely helps somebody who is stuck — a mnemonic, a category, a
 * root word — and left empty where it would only give the answer away.
 */
const card = (front, back, hint = '', tags = []) => ({ front, back, hint, tags });

export const usLibrary = [
  {
    title: 'US Citizenship Test: Civics',
    description: 'The civics questions asked at the naturalization interview, with the reasoning behind each answer rather than just the answer. Covers government, history, and the rights and duties of citizens.',
    color: 'violet', icon: 'globe', thumbnail: 'deck-civics.png',
    cards: [
      card('What is the supreme law of the land?', 'The Constitution. Every other law — federal, state or local — has to give way to it, which is what "supreme" is doing in that sentence.', '', ['government']),
      card('What does the Constitution do?', 'Three things: it sets up the government, it defines that government\'s powers, and it protects the basic rights of Americans. The third is the one people forget.', 'Sets up, defines, protects.', ['government']),
      card('The idea of self-government is in the first three words of the Constitution. What are they?', '"We the People." The point is that the government\'s authority comes from the governed, not from a monarch or a parliament.', '', ['government']),
      card('What is an amendment?', 'A change or addition to the Constitution. There have been 27 of them, which is remarkably few for a document written in 1787.', '', ['constitution']),
      card('What do we call the first ten amendments to the Constitution?', 'The Bill of Rights. They were added in 1791 because several states would only ratify the Constitution if explicit protections were promised.', '', ['constitution']),
      card('What is one right or freedom from the First Amendment?', 'Speech. Also religion, assembly, press, or petitioning the government — the First Amendment protects five freedoms in one sentence.', 'Five in one: think of RAPPS.', ['constitution']),
      card('How many amendments does the Constitution have?', 'Twenty-seven. The most recent, on congressional pay, was proposed in 1789 and not ratified until 1992.', '', ['constitution']),
      card('What did the Declaration of Independence do?', 'It announced that the thirteen colonies were free of British rule, and argued *why* a people may do that — which is the part Jefferson spent most of the words on.', '', ['history']),
      card('What are two rights in the Declaration of Independence?', 'Life and liberty. The third is the pursuit of happiness, which was a novel thing to put in a founding document.', '', ['history']),
      card('What is freedom of religion?', 'You may practise any religion, or none at all. The "or none" half is as protected as the rest.', '', ['constitution']),
      card('What is the economic system in the United States?', 'A capitalist, market economy. Prices and production are set largely by private decisions rather than by the state.', '', ['government']),
      card('What is the "rule of law"?', 'Nobody is above the law — including the people who make it and enforce it. The government is bound by the same rules as everyone else.', '', ['government']),
      card('Name one branch of the government.', 'Congress, the legislative branch. The other two are the executive (the President) and the judicial (the courts).', '', ['government']),
      card('What stops one branch of government from becoming too powerful?', 'Checks and balances, also called the separation of powers. Each branch can block some part of what the others do.', '', ['government']),
      card('Who is in charge of the executive branch?', 'The President. The executive branch carries out and enforces laws rather than writing them.', '', ['government']),
      card('Who makes federal laws?', 'Congress — the Senate and the House of Representatives together. A bill has to pass both before it reaches the President.', '', ['government']),
      card('What are the two parts of the US Congress?', 'The Senate and the House of Representatives. Two chambers was the compromise that let both small and large states accept the Constitution.', '', ['government']),
      card('How many US Senators are there?', 'One hundred — two from every state, regardless of population. That is why Wyoming and California have equal weight in the Senate.', 'Two per state, fifty states.', ['government']),
      card('We elect a US Senator for how many years?', 'Six. Terms are staggered so only about a third of the Senate is up for election at once.', '', ['government']),
      card('The House of Representatives has how many voting members?', 'Four hundred and thirty-five. The number has been fixed by law since 1929; seats are redistributed among the states after each census.', '', ['government']),
      card('We elect a US Representative for how many years?', 'Two. The whole House faces election every two years, which is meant to keep it close to public opinion.', '', ['government']),
      card('Why do some states have more Representatives than others?', 'Because representation in the House is based on population. Seats are reapportioned after every ten-yearly census.', '', ['government']),
      card('We elect a President for how many years?', 'Four. The Twenty-second Amendment limits a President to two elected terms.', '', ['government']),
      card('If the President can no longer serve, who becomes President?', 'The Vice President. After that the Speaker of the House, then the President pro tempore of the Senate.', '', ['government']),
      card('Who is the Commander in Chief of the military?', 'The President. Civilian control of the armed forces is deliberate: the person commanding them is elected, not a career officer.', '', ['government']),
      card('Who vetoes bills?', 'The President. Congress can override a veto with a two-thirds vote in both chambers.', '', ['government']),
      card('How many justices are on the Supreme Court?', 'Nine. The number is set by Congress, not the Constitution, and has changed several times in history.', '', ['government']),
      card('What does the judicial branch do?', 'It reviews and explains laws, resolves disputes, and decides whether a law conflicts with the Constitution.', '', ['government']),
      card('What is the highest court in the United States?', 'The Supreme Court. Its reading of the Constitution binds every other court in the country.', '', ['government']),
      card('Under our Constitution, some powers belong to the states. What is one?', 'Providing schooling and education. Also police, driver\'s licences, and zoning — the everyday things government does.', '', ['government']),
      card('What are two ways that Americans can participate in their democracy?', 'Vote, and join a political party. Others include writing to an official, joining a civic group, standing for office, or campaigning publicly.', '', ['citizenship']),
      card('When must all men register for the Selective Service?', 'At age eighteen, and until they turn twenty-six. Registration is required even though there has been no draft since 1973.', '', ['citizenship']),
      card('What is one responsibility that is only for United States citizens?', 'Serving on a jury. Voting in a federal election is the other — both are reserved to citizens.', '', ['citizenship']),
      card('What is one promise you make when you become a United States citizen?', 'To be loyal to the United States and to obey its Constitution and laws. The oath also includes giving up loyalty to other countries and defending the Constitution.', '', ['citizenship']),
      card('Who wrote the Declaration of Independence?', 'Thomas Jefferson, as the principal author, working from a committee\'s instructions and with edits from Congress.', '', ['history']),
      card('When was the Declaration of Independence adopted?', 'July 4, 1776 — which is why that is the date Americans celebrate rather than the day the war ended.', '', ['history']),
      card('There were thirteen original states. Name three.', 'Virginia, Massachusetts and New York. The rest: New Hampshire, Rhode Island, Connecticut, New Jersey, Pennsylvania, Delaware, Maryland, North Carolina, South Carolina and Georgia.', '', ['history']),
      card('What happened at the Constitutional Convention?', 'The Constitution was written, in Philadelphia in 1787. The delegates had gathered intending only to revise the Articles of Confederation and ended up replacing them.', '', ['history']),
      card('What is one thing Benjamin Franklin is famous for?', 'He was a US diplomat. Also: the oldest member of the Constitutional Convention, the first Postmaster General, and the author of Poor Richard\'s Almanack.', '', ['history']),
      card('Who is the "Father of Our Country"?', 'George Washington — for commanding the Continental Army and then, unusually, handing power back rather than keeping it.', '', ['history']),
      card('What territory did the United States buy from France in 1803?', 'The Louisiana Territory. It roughly doubled the size of the country for about fifteen million dollars.', '', ['history']),
      card('Name one war fought by the United States in the 1800s.', 'The Civil War. Also the War of 1812, the Mexican-American War and the Spanish-American War.', '', ['history']),
      card('Name one problem that led to the Civil War.', 'Slavery. Economic differences between North and South, and the argument over states\' rights, are the others usually given.', '', ['history']),
      card('What was one important thing that Abraham Lincoln did?', 'He freed the enslaved people through the Emancipation Proclamation. He also preserved the Union and led the country through the Civil War.', '', ['history']),
      card('What did the Emancipation Proclamation do?', 'It declared enslaved people in the rebelling states to be free. It did not by itself end slavery everywhere — the Thirteenth Amendment did that in 1865.', 'A wartime order, not an amendment.', ['history']),
      card('What did Susan B. Anthony do?', 'She fought for women\'s rights, and for civil rights more broadly. The amendment granting women the vote in 1920 is often named after her.', '', ['history']),
      card('Name one war fought by the United States in the 1900s.', 'World War Two. Also World War One, Korea, Vietnam and the Gulf War.', '', ['history']),
      card('Who was President during World War One?', 'Woodrow Wilson, who campaigned on staying out of it and then asked Congress to declare war in 1917.', '', ['history']),
      card('Who was President during the Great Depression and World War Two?', 'Franklin Roosevelt, the only President elected four times — which is why the two-term limit exists now.', '', ['history']),
      card('What did Martin Luther King Jr do?', 'He fought for civil rights, and worked for equality for all Americans, leading a movement built deliberately on non-violent protest.', '', ['history']),
      card('Name one state that borders Canada.', 'New York. Also Maine, New Hampshire, Vermont, Michigan, Ohio, Pennsylvania, Minnesota, North Dakota, Montana, Idaho, Washington and Alaska.', '', ['geography']),
      card('Name one state that borders Mexico.', 'California. The others are Arizona, New Mexico and Texas.', 'Four of them, west to east.', ['geography']),
      card('What is the capital of the United States?', 'Washington, D.C. The district is deliberately not part of any state, so no state could claim influence over the seat of government.', '', ['geography']),
      card('Where is the Statue of Liberty?', 'On Liberty Island in New York Harbor. It was a gift from France, dedicated in 1886.', '', ['geography']),
      card('Why does the flag have thirteen stripes?', 'One for each of the thirteen original colonies. The fifty stars are the fifty current states.', '', ['symbols']),
      card('What is the name of the national anthem?', '"The Star-Spangled Banner", written by Francis Scott Key after watching a British bombardment fail to take Fort McHenry in 1814.', '', ['symbols']),
      card('When do we celebrate Independence Day?', 'July 4. It marks the adoption of the Declaration of Independence, not the end of the war.', '', ['symbols']),
      card('Name two national US holidays.', 'Thanksgiving and Independence Day. Others include New Year\'s Day, Martin Luther King Jr Day, Memorial Day, Labor Day, Veterans Day and Christmas.', '', ['symbols']),
    ],
  },
  {
    title: 'SAT Vocabulary: High-Frequency Words',
    description: 'Words that keep appearing on the SAT reading and writing sections, each with what it means, how it is actually used in a sentence, and the root or trick that makes it stick.',
    color: 'orange', icon: 'book', thumbnail: 'deck-sat.png',
    cards: [
      card('ambivalent', 'Holding two opposing feelings at once. "She was ambivalent about the promotion — flattered by the offer, dreading the hours." Not the same as *indifferent*, which means not caring either way.', 'ambi- means both, as in ambidextrous.', ['adjectives']),
      card('candid', 'Frank and honest, often uncomfortably so. "A candid assessment of the draft" is one that tells you what is wrong with it.', 'Same root as *candle* — it means shining, unhidden.', ['adjectives']),
      card('pragmatic', 'Concerned with what works rather than what is ideal. "A pragmatic solution" may be inelegant but it ships.', '', ['adjectives']),
      card('austere', 'Severely plain, or sternly self-denying. Used of rooms, of budgets, and of people.', '', ['adjectives']),
      card('tenacious', 'Holding on firmly and refusing to let go. "A tenacious defender" keeps at it long after others would stop.', 'Think *tenant* — one who holds.', ['adjectives']),
      card('superfluous', 'More than is needed, to the point of being useless. "The final paragraph is superfluous" means cut it.', 'super- (over) + fluere (to flow): overflowing.', ['adjectives']),
      card('meticulous', 'Showing extreme care over detail. Positive where *fussy* is not.', '', ['adjectives']),
      card('ephemeral', 'Lasting a very short time. Used of fashions, of mayflies, of moods.', 'Greek for "lasting a day".', ['adjectives']),
      card('prudent', 'Careful and sensible about the future, especially about risk. "A prudent reserve" is money kept back in case.', '', ['adjectives']),
      card('obsolete', 'No longer in use because something better has replaced it. A fax machine is obsolete; a hammer is not.', '', ['adjectives']),
      card('arbitrary', 'Chosen on a whim rather than for a reason. "An arbitrary deadline" is one with no logic behind the date.', '', ['adjectives']),
      card('benevolent', 'Kindly, and inclined to do good for others. The opposite is *malevolent*.', 'bene- means well, as in benefit.', ['adjectives']),
      card('conspicuous', 'Very easy to notice, standing out. "Conspicuous by his absence" — the noticing is the point.', '', ['adjectives']),
      card('diligent', 'Working steadily and carefully. It describes persistence rather than brilliance.', '', ['adjectives']),
      card('eloquent', 'Fluent and persuasive in speech or writing. An eloquent argument is well made, not merely long.', '', ['adjectives']),
      card('frugal', 'Careful with money and resources, without being mean. "A frugal meal" is simple, not stingy.', '', ['adjectives']),
      card('novel', 'New and unlike what came before — as an adjective, nothing to do with books. "A novel approach" has not been tried.', 'Same root as *novelty*.', ['adjectives']),
      card('plausible', 'Seeming reasonable enough to be believed, whether or not it is true. "A plausible excuse" might still be a lie.', '', ['adjectives']),
      card('resilient', 'Able to recover quickly from difficulty, or to spring back into shape.', '', ['adjectives']),
      card('skeptical', 'Not easily convinced; inclined to question. Doubt held on purpose rather than out of ignorance.', '', ['adjectives']),
      card('advocate', 'To argue publicly in favour of something; or the person doing it. "She advocated for smaller classes."', 'ad- (towards) + vocare (to call).', ['verbs']),
      card('alleviate', 'To make something bad less severe. You alleviate pain or a shortage; you do not alleviate a problem away entirely.', 'Think *levity* — to lighten.', ['verbs']),
      card('undermine', 'To weaken something gradually, usually from underneath and often deliberately. "The leaks undermined the negotiation."', '', ['verbs']),
      card('scrutinize', 'To examine closely and critically. More than looking — looking for what is wrong.', '', ['verbs']),
      card('substantiate', 'To support a claim with evidence. "The allegation was never substantiated" means nobody produced proof.', '', ['verbs']),
      card('mitigate', 'To make less severe or less harmful. Often paired with *risk*.', 'Close to alleviate, but used for risks and consequences.', ['verbs']),
      card('refute', 'To prove a statement wrong. Note: *rebut* is to argue against; *refute* is to actually disprove.', '', ['verbs']),
      card('ambiguous', 'Open to more than one interpretation. Different from *ambivalent*, which is about feelings, not meanings.', 'Meanings, not moods.', ['adjectives']),
      card('inevitable', 'Certain to happen and impossible to avoid.', 'in- (not) + evitare (to avoid).', ['adjectives']),
      card('paradox', 'A statement that seems self-contradictory but contains a truth. "The more you know, the more you know you do not know."', '', ['nouns']),
      card('rhetoric', 'The art of persuasive speaking or writing; or, disapprovingly, language that is persuasive but empty. Context tells you which.', '', ['nouns']),
      card('consensus', 'General agreement across a group. Note the spelling — one *s* in the middle, from *consent*, not *census*.', '', ['nouns']),
    ],
  },
  {
    title: 'AP US History: Founding to Reconstruction',
    description: 'The events, documents and arguments that AP US History keeps returning to, from the colonial period through Reconstruction — with why each one mattered, not just when it happened.',
    color: 'slate', icon: 'layers', thumbnail: 'deck-apush.png',
    cards: [
      card('What was the Mayflower Compact, and why does it matter?', 'A 1620 agreement among the Plymouth settlers to govern themselves by majority decision. It matters as an early instance of government by consent in America, written before any charter authorised it.', '', ['colonial']),
      card('What were the Navigation Acts?', 'English laws requiring colonial trade to pass through English ships and ports. Loosely enforced for decades, which made later enforcement feel like a new imposition rather than an old rule.', '', ['colonial']),
      card('What was the significance of the Great Awakening?', 'A wave of religious revival in the 1730s and 40s that undercut established church authority and taught colonists to question institutions — a habit that transferred to politics.', '', ['colonial']),
      card('Why did the French and Indian War lead to friction with Britain?', 'Britain won but was left with enormous debt, and began taxing the colonies to pay it. It also removed the French threat that had made British protection feel necessary.', 'The war Britain won that cost it the colonies.', ['revolution']),
      card('What did the Stamp Act do, and why was the reaction so strong?', 'It taxed printed materials directly, rather than regulating trade. Colonists objected to the principle — a tax levied by a Parliament they had not elected.', '', ['revolution']),
      card('What does "no taxation without representation" actually claim?', 'That only a legislature in which you have chosen representatives may tax you. Britain answered with "virtual representation", arguing Parliament represented all subjects; colonists found that unconvincing.', '', ['revolution']),
      card('What were the Intolerable Acts a response to?', 'The Boston Tea Party. They closed Boston harbour and curtailed Massachusetts self-government, and by punishing a whole colony they pushed the others into common cause.', '', ['revolution']),
      card('What was the main weakness of the Articles of Confederation?', 'Congress could not tax or regulate commerce, and had no executive to enforce anything. It could ask the states for money and money; it could not compel either.', 'It could ask, not require.', ['founding']),
      card('What was Shays\' Rebellion, and what did it prove?', 'An armed uprising of indebted Massachusetts farmers in 1786–87. Putting it down required a private militia, which convinced many that the national government was too weak to survive.', '', ['founding']),
      card('What was the Great Compromise?', 'Representation by population in the House and equal representation in the Senate. It reconciled large and small states and is why Congress has two chambers.', '', ['founding']),
      card('What was the Three-Fifths Compromise?', 'Enslaved people were counted as three-fifths of a person for both representation and taxation. It gave the South extra seats in Congress while denying those counted any rights at all.', '', ['founding']),
      card('What divided Federalists from Anti-Federalists?', 'Whether a strong national government would protect liberty or threaten it. Anti-Federalist pressure is why the Bill of Rights was added.', '', ['founding']),
      card('What did Marbury v. Madison establish?', 'Judicial review — the Supreme Court\'s power to strike down laws that conflict with the Constitution. The Court asserted this power in a case it then declined to decide in its own favour.', '1803, Chief Justice Marshall.', ['early-republic']),
      card('What was the Missouri Compromise?', 'Missouri entered as a slave state and Maine as a free one, and slavery was barred north of 36°30′ in the Louisiana Territory. It kept the Senate balanced and postponed the argument for thirty years.', '', ['sectionalism']),
      card('What was the Monroe Doctrine?', 'An 1823 declaration that European powers should not interfere in the Americas, and that the US would stay out of European affairs. Unenforceable at the time, but it shaped a century of policy.', '', ['early-republic']),
      card('What was Manifest Destiny?', 'The belief that the United States was destined to expand across the continent. It supplied a moral vocabulary for westward expansion and for the removal of the people already there.', '', ['expansion']),
      card('What was the Trail of Tears?', 'The forced removal of the Cherokee and other nations to territory west of the Mississippi in the 1830s, after the Indian Removal Act. Thousands died on the journey.', '', ['expansion']),
      card('What was the Compromise of 1850?', 'California entered free, the slave trade ended in Washington D.C., and a far stricter Fugitive Slave Act was enacted. That last provision inflamed the North rather than settling anything.', '', ['sectionalism']),
      card('Why was the Kansas-Nebraska Act so destabilising?', 'It let settlers vote on slavery in territories where the Missouri Compromise had banned it. The result was armed conflict — "Bleeding Kansas" — and the collapse of the old party system.', 'Popular sovereignty in practice.', ['sectionalism']),
      card('What did the Dred Scott decision hold?', 'That African Americans were not citizens and could not sue, and that Congress could not ban slavery in the territories. It destroyed any legislative middle ground.', '', ['sectionalism']),
      card('Why did Lincoln\'s election trigger secession?', 'He was elected on a platform of halting slavery\'s expansion, without carrying a single Southern state. Southern leaders concluded the political route to protecting slavery was closed.', '', ['civil-war']),
      card('What did the Emancipation Proclamation actually do?', 'It declared enslaved people free in the rebelling states only — where the Union had no control. Its real effects were to make abolition a war aim and to deter European recognition of the Confederacy.', '', ['civil-war']),
      card('What was the significance of Gettysburg and Vicksburg?', 'Both fell in July 1863. Gettysburg ended Confederate invasion of the North; Vicksburg gave the Union the Mississippi and split the Confederacy in two.', '', ['civil-war']),
      card('What did the Thirteenth Amendment do?', 'Abolished slavery throughout the United States, in 1865. It finished what the Emancipation Proclamation could only declare.', 'Thirteen abolishes.', ['reconstruction']),
      card('What did the Fourteenth Amendment establish?', 'Birthright citizenship, equal protection of the laws, and due process against state action. It is the amendment most often litigated today.', 'Fourteen makes equal.', ['reconstruction']),
      card('What did the Fifteenth Amendment do?', 'Barred denying the vote on grounds of race. Literacy tests, poll taxes and violence then achieved the same exclusion by other means for nearly a century.', 'Fifteen gives the vote.', ['reconstruction']),
      card('What were the Black Codes?', 'Southern state laws passed just after the war restricting the freedoms of newly freed people — on work, movement and property. They prompted Congress into Radical Reconstruction.', '', ['reconstruction']),
      card('What was the Compromise of 1877?', 'The disputed 1876 election was resolved in Hayes\'s favour in exchange for withdrawing federal troops from the South. It ended Reconstruction and left enforcement of the new amendments to the states.', '', ['reconstruction']),
      card('What was sharecropping, and why did it persist?', 'Tenants farmed land for a share of the crop. Debt to the landowner usually exceeded the share, which tied families to the land almost as firmly as before.', '', ['reconstruction']),
      card('What did Plessy v. Ferguson decide?', 'That "separate but equal" facilities were constitutional, in 1896. It gave legal cover to segregation until Brown v. Board overturned it in 1954.', '', ['reconstruction']),
    ],
  },
  {
    title: 'AP Psychology: Core Concepts',
    description: 'The terms, studies and effects that AP Psychology tests hardest, each explained with the example that makes it obvious — plus the distinctions students most often mix up.',
    color: 'blue', icon: 'brain', thumbnail: 'deck-psych.png',
    cards: [
      card('What is the difference between classical and operant conditioning?', 'Classical pairs two stimuli so one comes to trigger a reflex — Pavlov\'s bell and salivation. Operant changes behaviour through its consequences — a rat pressing a lever for food. Classical is involuntary; operant is voluntary.', 'Classical: reflexes. Operant: choices.', ['learning']),
      card('What is negative reinforcement, and why is it not punishment?', 'Removing something unpleasant to increase a behaviour — taking aspirin to end a headache makes you take aspirin again. It *increases* behaviour; punishment decreases it. "Negative" means something is taken away, not that it is bad.', 'Negative = subtract, not bad.', ['learning']),
      card('Which reinforcement schedule produces the most persistent behaviour?', 'Variable ratio — reward after an unpredictable number of responses. It is the schedule slot machines use, and it is the hardest to extinguish.', '', ['learning']),
      card('What is the fundamental attribution error?', 'Overweighting personality and underweighting circumstance when explaining other people\'s behaviour. A driver who cuts you off is reckless; when you do it, you are late for something.', '', ['social']),
      card('What is cognitive dissonance?', 'The discomfort of holding beliefs that conflict with each other or with your behaviour — usually resolved by changing the belief rather than the behaviour. Festinger\'s work on this began with a doomsday cult whose prophecy failed.', '', ['social']),
      card('What did Milgram\'s obedience study find?', 'That about two thirds of ordinary participants would deliver what they believed were dangerous shocks when instructed by an authority figure. The finding was about situational pressure, not cruelty.', '', ['social']),
      card('What is the bystander effect?', 'The more witnesses to an emergency, the less likely any one of them intervenes — responsibility feels diffused across the group.', '', ['social']),
      card('What is groupthink?', 'When a group\'s desire for harmony suppresses dissent and realistic appraisal, producing worse decisions than its members would make alone.', '', ['social']),
      card('What is the difference between the sympathetic and parasympathetic nervous systems?', 'Sympathetic mobilises the body for action — heart rate up, pupils wide. Parasympathetic returns it to rest and digestion. They are the accelerator and the brake.', 'Sympathetic: stress. Parasympathetic: peace.', ['biology']),
      card('What does the hippocampus do?', 'Forms new explicit memories. Damage to it prevents laying down new facts and events while leaving old memories and learned skills intact.', '', ['biology']),
      card('What does the amygdala do?', 'Processes emotion, fear and threat especially, and tags experiences with emotional significance so they are remembered more strongly.', '', ['biology']),
      card('What is neuroplasticity?', 'The brain\'s capacity to reorganise — forming new connections and reassigning function — in response to learning or injury. It is greatest in childhood but never ends.', '', ['biology']),
      card('What are rods and cones?', 'Rods detect light and dark and work in dim conditions; cones detect colour and fine detail and need good light. It is why colour drains out of a dark room.', '', ['sensation']),
      card('What is the difference between sensation and perception?', 'Sensation is the raw signal the receptors send. Perception is the brain organising and interpreting it. The same sensation can yield different perceptions — which is what an optical illusion exploits.', '', ['sensation']),
      card('What is the cocktail party effect?', 'Selective attention: you can follow one conversation in a noisy room, and still notice your own name spoken across it.', '', ['sensation']),
      card('What is the capacity of working memory?', 'About four to seven items, briefly. Chunking raises the effective limit — a phone number is easier as three groups than as ten digits.', 'Miller said seven plus or minus two.', ['memory']),
      card('What is the difference between proactive and retroactive interference?', 'Proactive: old learning disrupts new — your previous password keeps coming out. Retroactive: new learning disrupts old — the new password makes the old one unrecallable.', 'Pro- comes first and pushes forward.', ['memory']),
      card('What is the serial position effect?', 'Items at the start and end of a list are recalled best. Primacy comes from rehearsal into long-term memory; recency from still being in working memory.', '', ['memory']),
      card('What is the spacing effect?', 'Material reviewed across spread-out sessions is retained far better than the same total time crammed. It is the finding this entire app is built on.', '', ['memory']),
      card('What is the difference between explicit and implicit memory?', 'Explicit is what you can state — facts and events. Implicit is what you can do without stating it, like riding a bicycle. Different brain systems handle each.', '', ['memory']),
      card('What is confirmation bias?', 'Seeking and weighting evidence that supports what you already believe, while discounting what does not.', '', ['cognition']),
      card('What is the availability heuristic?', 'Judging how likely something is by how easily examples come to mind. It is why people overestimate plane crashes and underestimate heart disease.', '', ['cognition']),
      card('What is functional fixedness?', 'Being unable to see an object used any way but its usual one — failing to notice a coin could work as a screwdriver.', '', ['cognition']),
      card('What is the difference between reliability and validity?', 'Reliability is consistency — the same result on repetition. Validity is accuracy — measuring what you claim to measure. A broken scale reading five kilos heavy every time is reliable but not valid.', 'Reliable: repeatable. Valid: correct.', ['research']),
      card('Why is random assignment essential to an experiment?', 'It distributes pre-existing differences evenly across conditions, which is what allows a causal claim. Random *sampling* is a separate thing — that is about generalising to a population.', 'Assignment for cause; sampling for generalisation.', ['research']),
      card('What is a double-blind procedure?', 'Neither participants nor the researchers interacting with them know who is in which condition, so neither expectation can shape the result.', '', ['research']),
      card('What is the difference between a correlation and a cause?', 'A correlation says two things vary together; it cannot say which causes which, or whether a third factor causes both. Only a controlled experiment supports a causal claim.', '', ['research']),
      card('What are the stages of Piaget\'s cognitive development?', 'Sensorimotor, preoperational, concrete operational, formal operational. Object permanence appears in the first; abstract reasoning in the last.', '', ['development']),
      card('What is secure attachment, and how was it measured?', 'A child who explores confidently with a caregiver present, is distressed at separation and comforted on return. Ainsworth\'s Strange Situation is the procedure that identified it.', '', ['development']),
      card('What is the difference between Type I and Type II error?', 'Type I is a false positive — concluding an effect exists when it does not. Type II is a false negative — missing a real effect.', 'One is crying wolf; two is missing the wolf.', ['research']),
    ],
  },
  {
    title: 'MCAT Biochemistry: Amino Acids and Proteins',
    description: 'The twenty amino acids and the levels of protein structure, organised the way MCAT questions actually come at them — by property and by behaviour at physiological pH rather than alphabetically.',
    color: 'green', icon: 'flask', thumbnail: 'deck-mcat.png',
    cards: [
      card('What are the four groups attached to the alpha carbon of an amino acid?', 'An amino group, a carboxyl group, a hydrogen, and the R side chain. Because all four differ, the alpha carbon is a stereocentre in every amino acid except glycine.', '', ['structure']),
      card('Which amino acid is achiral, and why?', 'Glycine. Its side chain is a hydrogen, so the alpha carbon carries two identical substituents and cannot be a stereocentre.', 'The smallest one.', ['structure']),
      card('Which amino acids are nonpolar and aliphatic?', 'Glycine, alanine, valine, leucine, isoleucine, proline and methionine. These cluster in the hydrophobic interior of a folded protein.', '', ['classification']),
      card('Which amino acids are aromatic?', 'Phenylalanine, tyrosine and tryptophan. Their rings absorb ultraviolet light near 280 nm, which is how protein concentration is measured.', 'Phe, Tyr, Trp — the reason A280 works.', ['classification']),
      card('Which amino acids carry a negative charge at physiological pH?', 'Aspartate and glutamate. Their carboxylate side chains have pKa values near 4, so at pH 7.4 they are deprotonated.', '', ['charge']),
      card('Which amino acids carry a positive charge at physiological pH?', 'Lysine and arginine, reliably. Histidine has a side-chain pKa near 6, so it is only partly protonated at 7.4 — which is exactly what makes it useful in enzyme active sites.', '', ['charge']),
      card('Why is histidine so often found in enzyme active sites?', 'Its pKa of about 6 sits close to physiological pH, so it can accept or donate a proton under cellular conditions. Most other side chains are locked in one state.', 'The only one that can go either way at pH 7.', ['charge']),
      card('Which amino acids contain sulphur?', 'Cysteine and methionine. Only cysteine can form disulphide bonds; methionine\'s sulphur is in a thioether and cannot.', '', ['classification']),
      card('What is a disulphide bond, and why does it matter?', 'A covalent link between two cysteine side chains, formed by oxidation. It is the only covalent bond in tertiary structure and stabilises proteins that work outside the reducing cytosol.', '', ['structure']),
      card('Which amino acid disrupts alpha helices, and why?', 'Proline. Its side chain bonds back to the backbone nitrogen, which both removes the amide hydrogen needed for helical hydrogen bonding and imposes a rigid kink.', 'The one with a ring in the backbone.', ['structure']),
      card('Which amino acids are hydroxyl-bearing and commonly phosphorylated?', 'Serine, threonine and tyrosine. Kinases transfer a phosphate onto these hydroxyls, which is the basis of most signal transduction.', '', ['classification']),
      card('Which amino acids have amide side chains?', 'Asparagine and glutamine — the uncharged amide relatives of aspartate and glutamate. Polar but never charged, at any pH.', 'Asn and Gln: the neutral cousins.', ['classification']),
      card('What is the isoelectric point?', 'The pH at which a molecule carries no net charge. On electrophoresis an amino acid stops moving at its pI, which is how the technique separates them.', '', ['charge']),
      card('How do you estimate the pI of a neutral amino acid?', 'Average the two pKa values flanking the neutral form — roughly 2 for the carboxyl and 9 for the amino group, giving a pI near 6.', '', ['charge']),
      card('What defines primary structure?', 'The sequence of amino acids joined by peptide bonds, written N-terminus to C-terminus. Everything else follows from it.', '', ['protein-structure']),
      card('What holds secondary structure together?', 'Hydrogen bonds between backbone amide and carbonyl groups — not side chains. That is why alpha helices and beta sheets look similar in very different proteins.', 'Backbone, not side chains.', ['protein-structure']),
      card('What forces determine tertiary structure?', 'Side-chain interactions: hydrophobic packing above all, plus hydrogen bonds, ionic pairs and disulphide bridges. Burying hydrophobic residues away from water is the dominant driving force.', '', ['protein-structure']),
      card('What is quaternary structure?', 'The assembly of two or more folded polypeptide chains into one functional unit. Haemoglobin, with four subunits, is the standard example.', '', ['protein-structure']),
      card('What is the peptide bond, and why is it planar?', 'An amide between one residue\'s carboxyl and the next one\'s amino group. Resonance gives it partial double-bond character, so rotation is restricted and the unit stays flat.', '', ['structure']),
      card('What is denaturation?', 'Loss of a protein\'s folded structure — and so its function — without breaking peptide bonds. Heat, extreme pH, urea and detergents all do it.', 'Shape is lost; sequence is not.', ['protein-structure']),
      card('Why does haemoglobin show cooperative binding?', 'Binding oxygen at one subunit shifts the others from the low-affinity T state towards the high-affinity R state, so affinity rises with saturation. The result is a sigmoidal curve rather than myoglobin\'s hyperbola.', '', ['proteins']),
      card('What does the Bohr effect describe?', 'Falling pH reduces haemoglobin\'s oxygen affinity, so actively respiring tissue — acidic with carbon dioxide — gets oxygen released where it is needed.', '', ['proteins']),
      card('Which amino acids are ketogenic only?', 'Leucine and lysine. Both letters begin with L, which is the usual way to remember it.', 'Both start with L.', ['metabolism']),
      card('What is the difference between essential and non-essential amino acids?', 'Essential ones cannot be synthesised by the body and must come from the diet — nine of the twenty. Non-essential can be made from other metabolites.', '', ['metabolism']),
      card('Why is the hydrophobic effect entropically driven?', 'Water forms an ordered cage around an exposed nonpolar surface. Burying those surfaces releases that structured water into the bulk, and the entropy gain of the water — not the protein — drives folding.', 'The entropy that increases is the water\'s.', ['protein-structure']),
    ],
  },
];
