import { useState } from 'react';
import { Link2, Check, LockKeyhole, Globe2, UserPlus, ShieldCheck, Copy } from 'lucide-react';
import { toast } from 'sonner';
import { Modal, Avatar, Field, Button, ErrorState } from './ui';
import { useApp } from '../hooks/useApp';
import { api } from '../services/api';
import Select from './Select';
import { hasPremium } from '../../../shared/account.js';
import { useNavigate } from 'react-router-dom';
export default function ShareModal({ folder: initial, onClose }) {
  const { refresh, isDemo, user } = useApp(); const navigate = useNavigate(); const [folder, setFolder] = useState(initial), [username, setUsername] = useState(''), [role, setRole] = useState('viewer'), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const owner = folder.role === 'owner';
  async function member(name, value) { if (value === 'editor' && !hasPremium(user)) { onClose(); navigate('/premium'); return; } setBusy(true); setError(''); try { const d = await api(`/folders/${folder.id}/members`, { method: 'POST', body: { username: name.replace(/^@/, '').toLowerCase().trim(), role: value } }); setFolder(d.folder); setUsername(''); refresh(); toast.success(isDemo ? 'Preview access updated' : value === 'remove' ? 'Access removed' : 'Folder access updated'); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function visibility(value) { setBusy(true); try { const d = await api(`/folders/${folder.id}`, { method: 'PATCH', body: { title: folder.title, description: folder.description, color: folder.color, icon: folder.icon, visibility: value, version: folder.version } }); setFolder(d.folder); refresh(); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  return <Modal open onClose={onClose} title={`Share “${folder.title}”`} description="Good things are better when you learn together."><div className="form-stack">{isDemo && <div className="inline-note">Preview only: try @alex or @maya. No invitations are sent.</div>}{owner && <form className="invite-form" onSubmit={e => { e.preventDefault(); member(username, role); }}><label className="username-input"><span>@</span><input aria-label="Collaborator username" required placeholder="Add by username" value={username} onChange={e => setUsername(e.target.value)} pattern="@?[a-zA-Z0-9_]{3,24}"/></label><Select compact label="Invite role" value={role} onChange={setRole} options={[{ value: 'viewer', label: 'Viewer' }, { value: 'editor', label: `Editor${hasPremium(user) ? '' : ' · Premium'}` }]}/><Button className="primary" loading={busy} type="submit">Add</Button></form>}<div><span className="input-label">People with access</span><div className="member-row"><Avatar user={folder.owner}/><div><strong>{folder.owner?.name}</strong><small>@{folder.owner?.username}</small></div><span className="muted">Owner</span></div>{folder.members?.map(m => <div className="member-row" key={m.user.id}><Avatar user={m.user}/><div><strong>{m.user.name}</strong><small>@{m.user.username}</small></div>{owner ? <Select compact disabled={busy} label={`Role for ${m.user.username}`} value={m.role} onChange={v => member(m.user.username, v)} options={[{ value: 'viewer', label: 'Viewer' }, { value: 'editor', label: 'Editor' }, { value: 'remove', label: 'Remove access' }]}/> : <span className="muted">{m.role}</span>}</div>)}</div><div className="share-access"><div className="share-access-icon">{folder.visibility === 'global' ? <Globe2 size={22}/> : <LockKeyhole size={22}/>}</div><div><strong>{folder.visibility === 'global' ? 'Available to everyone' : 'Only invited people'}</strong><p>{folder.visibility === 'global' ? 'Anyone can view and study. Editing requires an invitation.' : 'Only the owner and invited people can open this folder.'}</p></div>{owner && <Select compact label="Folder visibility" disabled={busy} value={folder.visibility} onChange={visibility} options={[{ value: 'private', label: 'Private' }, { value: 'global', label: 'Global' }]}/>}</div>{error && <ErrorState message={error}/>}<div className="sharing-note"><ShieldCheck size={17}/><span>Everyone keeps their own study progress.</span></div><div className="modal-actions"><Button className="secondary" onClick={async () => { try { await navigator.clipboard.writeText(`${location.origin}/folders/${folder.id}`); toast.success('Link copied'); } catch { setError('Clipboard unavailable. Copy the folder URL from your browser.'); } }}><Link2 size={17}/> Copy link</Button><Button className="primary" onClick={onClose}>Done <Check size={17}/></Button></div></div></Modal>;
}
